spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${db_password}
    username: ${db_username}
    url: jdbc:mysql://${db_host:localhost}:${db_port:3306}/restaurant?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${smtp_username}
    password: ${smtp_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    com.lididimi.restaurant: DEBUG
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
  file:
    path: /
    name: appLog.log
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8082
  
categories:
  api:
    baseUrl: "${categories_base_url}"

cloudinary:
  cloud-name: ${cloudinary.cloud-name}
  api-key: ${cloudinary.api-key}
  api-secret: ${cloudinary.api-secret}

bills.retention.period: P1Y

jwt:
  secret: ${jwt_key:WSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8I}
  expiration: ${jwt_expiration:36000000}

